---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "eval-service"
  namespace: "evaluacion"
---
spec:
  selector:
    app: "eval-test"
  ports:
    - port: 80
      targetPort: 8000
  type: "LoadBalancer"